rickwest/devsnippets

- source/snippets/dockerce-ubuntu.md
I've added a snippet that shows how to install Docker-CE on Ubuntu.
> Adding a snippet on how to install Docker-CE nix

- CONTRIBUTORS.md
- readme.md
- source/snippets/git/index.md
- Linting removed some EOL spacing
- Added git branching shortcuts I use all the time personally
- Added to contributors file
- ReadMe now has a link to the homepage as not everyone knows where PHP routes are defined 😃
> Git branching shortcuts

- source/snippets/react/index.md
Added react input component, as the user types it will display their input on the screen and save it in state.
> react input component

- CONTRIBUTORS.md
- source/snippets/vue/index.md
Ref: https://github.com/rickwest/devsnippets/issues/6
Add new snippet for Vue.
> Add Snippet Loop for Vue

- CONTRIBUTORS.md
- source/snippets/docker/index.md
Adding some useful snippets that safe some time and disk space from time to time.
> Adding docker snippets

- source/snippets/git/index.md
added mkdir and touch commands to git file
> add to git file

- CONTRIBUTORS.md
- source/snippets/javascript/index.md
https://github.com/rickwest/devsnippets
*** 
Signed-off-by: Mikee Ramirez miguel.ramirez@nowports.com
> Feat: added snippets for js context

- CONTRIBUTORS.md
- source/snippets/git/index.md
Added Merge and delete branch snippets
> Updated git snippet

- CONTRIBUTORS.md
- navigation.php
- source/snippets/git/index.md
useful git commands added below:
- git status
-git add
-git commit
> Cool snippet branch

- source/snippets/csharp/shuffle.md
- source/snippets/git/index.md
Maybe I'm able to merge now :+1:
> Some snippest added

- source/snippets/javascript/index.md
Added split(), join() and reverse() methods, including examples of how to use by themselves and together.
> Added some javascript methods and examples of use

- source/snippets/php/arrays.md
Added some more functions to the arrays section of PHP Snippets. Kindly review.
> Updated the Arrays section of PHP

- CONTRIBUTORS.md
- source/snippets/php/arrays.md
To resolve issue: #6 
Added two code snippets in arrays.md:
-> Multi-dimensional arrays
-> Multi-dimensional associative arrays
> Added 2 code snippets in php

- CONTRIBUTORS.md
- source/snippets/javascript/index.md
Adding new code snippet under the JavaScript Section. I've added a method using replace() method to get a plain text from a html text. It will take out any html tags and will return a plain text. sample code has also been added.
> Adding new code snippet in JS

- CONTRIBUTORS.md
- source/snippets/javascript/index.md
added javascript .filter() & .reduce() snippets with example.
> added .filter() & .reduce() snippets

- source/snippets/javascript/index.md
Uses card suits in the example.
> Simple While Loop to check for a string

- CONTRIBUTORS.md
- source/snippets/javascript/index.md
Describe the closures in Javascript
> Added the closures snippet for Javascript

- source/snippets/docker/index.md
thought you might want to improve the docker section with a small cheatsheet
> docker cheatsheet

- source/snippets/react/index.md
> added useThrottle hook to snippets

- .gitignore
- source/snippets/javascript/index.md
I talked about use of template string in JS
> About template-strings

- navigation.php
- source/snippets/java/index.md
I added a page about java, talking about strongly typed variables and println method.
> Add java page

- CONTRIBUTORS.md
- source/snippets/javascript/index.md
-Add/Sub time period to/from a Date variable
-White-list Checker
-Random generator
> Add some javascript snippets

- .gitignore
- CONTRIBUTORS.md
- source/snippets/javascript/index.md
A simples and initial explanation about objects and your uses.
> About objects

- source/snippets/javascript/contributing.md
- source/snippets/javascript/index.md
I've added a few commits in this one. I won't take it personally if you want to push back on any of this, and also understand if you're too busy to review thoroughly right now. I do have about 20 years of experience writing documentation :)
> Javascript improvements corrections

- source/snippets/vim/index.md
Fixed spelling and incorrect markdown.
Added additional sections to the article on insertion, copy/paste, and Vim macros.
> update vim article

- source/snippets/php/datetime.md
I have updated the Date and Time file with the strtotime() function and some examples. Kindly review :)
> Updated PHP Date and Time with strtotime() function

- source/snippets/react/index.md
React snippet of functional context provider component with useState hook.
> React snippet of functional context provider component with useState hook.

- CONTRIBUTORS.md
- source/snippets/react/index.md
simple reactDOM render snippet
> ReactDOM.Render added

- source/snippets/git/index.md
- Clone a remote branch locally
- Push local branch to remote
- Delete a remote branch
Please review
> Added some git snippets

- source/snippets/vim/index.md
Added word movements, visual mode selections, and some refactoring. 
😀
> Added movements, visual mode and edits

- source/snippets/php/datetime.md
> Updated Date folder

- CONTRIBUTORS.md
- navigation.php
- package-lock.json
- source/snippets/css/index.md
> added css snippet

- source/snippets/css/index.md
It's a contentious issue but I personally find it helpful to know what the usual breakpoints are for mobile, tablet and desktop devices. I also included a link to the CSS Tricks page where people can find device-specific media queries.
> Added CSS device media queries snippets

- source/snippets/git/index.md
> [Hacktoberfest] Add git commit amend snippet

- source/snippets/python/index.md
> AddedAdvice.md

- source/snippets/python/index.md
added snippet for function to determine if string is palindrome in python
> added snippet

- navigation.php
- source/snippets/bash/index.md
Adding some basics bash snippets
> Bash Snippets

- CONTRIBUTORS.md
- navigation.php
- source/snippets/go/index.md
Adding some basics golang snippets.
> add go snippets

- source/snippets/react/index.md
Map to render component to each array item
> React - Map rendering

- source/snippets/javascript/index.md
Explain the term Async/Await, some of its benefits, an example of a common pitfall and lastly, error handling when using this syntax.
> Add JavaScript snippets on Async/Await

- CONTRIBUTORS.md
- navigation.php
- source/snippets/css/index.md
- source/snippets/javascript/index.md
- source/snippets/react/index.md
- source/snippets/ruby/arrays.md
Hi Rick,
I was searching for open source projects to contribute and I'm glad I found yours. 
I have added code snippets for React, Javascript, CSS, and Ruby. 
I hope you find it useful. I'll try contributing, even more, when I could find the time. 
Thanks and All the best for your project
> Snippets added for React, JS, CSS and Ruby by Subbu Swaroop

- source/snippets/javascript/index.md
Add a new JS section to show examples of different use-cases for Array and Object Destructuring.
> Add new JavaScript snippets Destructuring 

- CONTRIBUTORS.md
- source/snippets/c/index.md
- source/snippets/python/index.md
> Added Python Snippets

- CONTRIBUTORS.md
- navigation.php
- source/snippets/php/filesystem.md
Add Human Readable File System.
Happy hackoctoberfest.
> Add File System Snippets Section (with Human Readable File Size)

- source/snippets/bash/index.md
some formatting changes were made by prettier automatically but nothing major it just added new lines between each header. I added snippets for Deleting folders and files, and to find processes using ports and kill them.
> add a few bash snippets

- CONTRIBUTORS.md
- source/snippets/vue/index.md
Vue 3 is now stable! So I figured I would add some snippets here.
> Add Vue 3 Snippets

- source/snippets/python/index.md
> Added new Python codes for different functions

- CONTRIBUTORS.md
- source/snippets/csharp/index.md
Program for finding minimum and maximum number.
> Max & Min No.
